import type { Metadata } from "next";
import "./globals.css";
import ProductsContextProvider from "@/context/ProductsContext";
import { CartContextProvider } from "@/context/CartContex";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ProductsContextProvider>
          <CartContextProvider>{children}</CartContextProvider>
        </ProductsContextProvider>
      </body>
    </html>
  );
}
